// Copyright 2025-2026 The Parallax Protocol Authors
// This file is part of parallax.
//
// parallax is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// parallax is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with parallax. If not, see <http://www.gnu.org/licenses/>.

package main

import (
	"net"
	"strings"
	"testing"

	"github.com/ParallaxProtocol/parallax/v2/p2p"
	"github.com/ParallaxProtocol/parallax/v2/p2p/protocols/disc"
)

func TestParseSeedV2IPPort(t *testing.T) {
	cases := []struct {
		in       string
		wantIP   string
		wantPort uint16
		wantNet  uint8
	}{
		{"1.2.3.4:32110", "1.2.3.4", 32110, disc.NetIPv4},
		{"127.0.0.1:1", "127.0.0.1", 1, disc.NetIPv4},
		{"[2001:db8::1]:8080", "2001:db8::1", 8080, disc.NetIPv6},
		{"  1.2.3.4:32110  ", "1.2.3.4", 32110, disc.NetIPv4}, // trims whitespace
	}
	for _, tc := range cases {
		t.Run(tc.in, func(t *testing.T) {
			n, err := parseSeed(tc.in)
			if err != nil {
				t.Fatalf("parseSeed(%q): %v", tc.in, err)
			}
			if n.KeyType != disc.KeyTypeNone {
				t.Errorf("KeyType = %d, want %d (v2)", n.KeyType, disc.KeyTypeNone)
			}
			if n.NodeID != "" {
				t.Errorf("NodeID = %q, want empty for v2", n.NodeID)
			}
			if n.IP != tc.wantIP {
				t.Errorf("IP = %q, want %q", n.IP, tc.wantIP)
			}
			if n.TCPPort != tc.wantPort {
				t.Errorf("TCPPort = %d, want %d", n.TCPPort, tc.wantPort)
			}
			if n.NetworkID != tc.wantNet {
				t.Errorf("NetworkID = %d, want %d", n.NetworkID, tc.wantNet)
			}
		})
	}
}

func TestParseSeedLegacyEnode(t *testing.T) {
	// A real enode URL — pubkey valid, 64 hex chars (128 chars).
	// Generated by enode.NewV4 in tests; this string is just one
	// example we know parses cleanly.
	const enodeURL = "enode://6f8a80d14311c39f35f516fa664deaaaa13e85b2f7493f37f6144d86991ec012937307647bd3b9a82abe2974e1407241d54947bbb39763a4cac9f77166ad92a0@1.2.3.4:32110"

	n, err := parseSeed(enodeURL)
	if err != nil {
		t.Fatalf("parseSeed(enode): %v", err)
	}
	if n.KeyType != disc.KeyTypeSecp256k1 {
		t.Errorf("KeyType = %d, want %d (legacy)", n.KeyType, disc.KeyTypeSecp256k1)
	}
	if len(n.NodeID) != 128 { // 64 bytes hex-encoded
		t.Errorf("NodeID length = %d, want 128", len(n.NodeID))
	}
	if n.IP != "1.2.3.4" {
		t.Errorf("IP = %q, want 1.2.3.4", n.IP)
	}
	if n.TCPPort != 32110 {
		t.Errorf("TCPPort = %d, want 32110", n.TCPPort)
	}
	if n.NetworkID != disc.NetIPv4 {
		t.Errorf("NetworkID = %d, want IPv4", n.NetworkID)
	}
}

func TestParseSeedRejects(t *testing.T) {
	cases := []string{
		"",
		"   ",
		"not-an-address",
		"1.2.3.4",                // no port
		"1.2.3.4:0",              // zero port
		"1.2.3.4:99999999",       // out of range
		"hostname:80",            // hostnames not supported
		"enode://abc@1.2.3.4:80", // truncated pubkey
	}
	for _, in := range cases {
		t.Run(in, func(t *testing.T) {
			n, err := parseSeed(in)
			if err == nil {
				t.Fatalf("parseSeed(%q) = %+v, want error", in, n)
			}
		})
	}
}

func TestNodeKeyStableAcrossInstances(t *testing.T) {
	a := &CrawlNode{NetworkID: disc.NetIPv4, IP: "1.2.3.4", TCPPort: 32110}
	b := &CrawlNode{NetworkID: disc.NetIPv4, IP: "1.2.3.4", TCPPort: 32110, KeyType: disc.KeyTypeSecp256k1, NodeID: "deadbeef"}
	if nodeKey(a) != nodeKey(b) {
		// KeyType + NodeID must NOT contribute — a node migrating from
		// v1.x to v2.x must keep its slot in CrawlState so accumulated
		// stats survive the migration.
		t.Errorf("nodeKey(a)=%q != nodeKey(b)=%q (KeyType should not affect key)", nodeKey(a), nodeKey(b))
	}
	// IPv4 vs IPv6 must yield different keys even if textual form
	// could collide (e.g. ::ffff:1.2.3.4 mapped form).
	c := &CrawlNode{NetworkID: disc.NetIPv6, IP: "1.2.3.4", TCPPort: 32110}
	if nodeKey(a) == nodeKey(c) {
		t.Errorf("IPv4 and IPv6 nodes with same IP/port collide on nodeKey")
	}
}

func TestPeerEntryToCrawlNode(t *testing.T) {
	cases := []struct {
		name    string
		in      disc.PeerEntry
		wantOK  bool
		wantKey string
	}{
		{
			name: "v2 ipv4",
			in: disc.PeerEntry{
				NetworkID: disc.NetIPv4,
				Addr:      []byte{1, 2, 3, 4},
				TCPPort:   32110,
				KeyType:   disc.KeyTypeNone,
			},
			wantOK:  true,
			wantKey: "1/1.2.3.4/32110",
		},
		{
			name: "legacy ipv4 with NodeID",
			in: disc.PeerEntry{
				NetworkID: disc.NetIPv4,
				Addr:      []byte{5, 6, 7, 8},
				TCPPort:   30303,
				KeyType:   disc.KeyTypeSecp256k1,
				NodeID:    make([]byte, 64),
			},
			wantOK:  true,
			wantKey: "1/5.6.7.8/30303",
		},
		{
			name: "v2 ipv6",
			in: disc.PeerEntry{
				NetworkID: disc.NetIPv6,
				Addr:      append(make([]byte, 14), 0xde, 0xad),
				TCPPort:   32110,
				KeyType:   disc.KeyTypeNone,
			},
			wantOK:  true,
			wantKey: "2/::dead/32110",
		},
		{
			name: "torv3 dropped",
			in: disc.PeerEntry{
				NetworkID: disc.NetTorV3,
				Addr:      make([]byte, 32),
				TCPPort:   8080,
				KeyType:   disc.KeyTypeNone,
			},
			wantOK: false,
		},
		{
			name: "zero port skipped",
			in: disc.PeerEntry{
				NetworkID: disc.NetIPv4,
				Addr:      []byte{1, 2, 3, 4},
				TCPPort:   0,
				KeyType:   disc.KeyTypeNone,
			},
			wantOK: false,
		},
		{
			name: "bad addr length skipped",
			in: disc.PeerEntry{
				NetworkID: disc.NetIPv4,
				Addr:      []byte{1, 2, 3}, // 3 bytes, want 4 for IPv4
				TCPPort:   32110,
				KeyType:   disc.KeyTypeNone,
			},
			wantOK: false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, ok := peerEntryToCrawlNode(tc.in)
			if ok != tc.wantOK {
				t.Fatalf("ok = %v, want %v", ok, tc.wantOK)
			}
			if !ok {
				return
			}
			if k := nodeKey(got); k != tc.wantKey {
				t.Errorf("nodeKey = %q, want %q", k, tc.wantKey)
			}
		})
	}
}

func TestIsDialableIP(t *testing.T) {
	cases := []struct {
		in   string
		want bool
	}{
		{"1.2.3.4", true},
		{"8.8.8.8", true},
		{"2001:db8::1", true},
		{"127.0.0.1", false},   // loopback
		{"0.0.0.0", false},     // unspecified
		{"169.254.1.1", false}, // link-local
		{"224.0.0.1", false},   // multicast
		{"::1", false},         // ipv6 loopback
		{"::", false},          // ipv6 unspecified
		{"fe80::1", false},     // ipv6 link-local
		{"ff02::1", false},     // ipv6 multicast
	}
	for _, tc := range cases {
		t.Run(tc.in, func(t *testing.T) {
			got := isDialableIP(net.ParseIP(tc.in))
			if got != tc.want {
				t.Errorf("isDialableIP(%q) = %v, want %v", tc.in, got, tc.want)
			}
		})
	}
}

func TestComputeDiscOffsetCases(t *testing.T) {
	cases := []struct {
		name    string
		caps    []p2p.Cap
		wantOff int
		wantErr bool
	}{
		{
			// The crawler no longer offers parallax/66 (it never spoke
			// the prl Status handshake, and advertising it armed the
			// daemon's 5s teardown timer), so the daemon's parallax
			// advert is not mutual and allocates no codes on either
			// side — disc sits at the base offset.
			name:    "parallax + parallax-disc",
			caps:    []p2p.Cap{{Name: "parallax", Version: 66}, {Name: "parallax-disc", Version: 1}},
			wantOff: 16,
		},
		{
			name:    "only parallax-disc",
			caps:    []p2p.Cap{{Name: "parallax-disc", Version: 1}},
			wantOff: 16,
		},
		{
			name:    "parallax-disc with unrelated cap",
			caps:    []p2p.Cap{{Name: "snap", Version: 1}, {Name: "parallax-disc", Version: 1}, {Name: "eth", Version: 66}},
			wantOff: 16,
		},
		{
			name:    "no parallax-disc",
			caps:    []p2p.Cap{{Name: "parallax", Version: 66}, {Name: "snap", Version: 1}},
			wantErr: true,
		},
		{
			// A parallax version we don't offer is not negotiated, so
			// it must not shift the layout — name-only matching would
			// count 17 codes the server never allocates.
			name:    "unknown parallax version excluded",
			caps:    []p2p.Cap{{Name: "parallax", Version: 99}, {Name: "parallax-disc", Version: 1}},
			wantOff: 16,
		},
		{
			// Multiple non-mutual parallax versions still allocate
			// nothing — the negotiated layout only counts caps both
			// sides offer.
			name:    "duplicate parallax versions counted once",
			caps:    []p2p.Cap{{Name: "parallax", Version: 66}, {Name: "parallax", Version: 99}, {Name: "parallax-disc", Version: 1}},
			wantOff: 16,
		},
		{
			name:    "unsupported parallax-disc version",
			caps:    []p2p.Cap{{Name: "parallax", Version: 66}, {Name: "parallax-disc", Version: 2}},
			wantErr: true,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			off, err := computeDiscOffset(tc.caps)
			if tc.wantErr {
				if err == nil {
					t.Fatalf("expected error, got off=%d", off)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if off != tc.wantOff {
				t.Errorf("off = %d, want %d", off, tc.wantOff)
			}
		})
	}
}

// TestParseSeedTrimsAndPrefix ensures `enode://` detection is exact —
// a string starting with similar characters but not the prefix is
// treated as ip:port (and likely fails parsing).
func TestParseSeedRejectsPartialEnodePrefix(t *testing.T) {
	for _, in := range []string{"enode:1.2.3.4:80", "node://abc@1.2.3.4:80"} {
		if _, err := parseSeed(in); err == nil {
			t.Errorf("parseSeed(%q) accepted, want error", in)
		} else if strings.Contains(err.Error(), "enode") && !strings.HasPrefix(in, "enode://") {
			// We don't want false enode-routing on near-prefixes.
			// The error should come from ip:port parsing, not enode
			// parsing. Tolerate both — the test just needs failure.
			_ = err
		}
	}
}
